### ISSUE TITLE
Paper results are not reproduced

### ISSUE THREAD

**Issue by khanrc** [VSumanth99/InferenceTimeDG#3]
Dear authors, thank you for the work,
I've been trying to reproduce results of the paper. I used `pacs_resnet_FNet.py` and `pacs_resnet_Gphi_projection.py` to reproduce the ResNet18 results, only modifying source and target domains properly. However, the results are very poor. How to reproduce the results of the paper?

And, I found the experiment takes too long. It takes about two days for a single run and single target domain in PACS dataset, which is about 50 times slower than the usual domain generalization methods. Is this speed same speed you experimented?

**Comment by prinshul** [comment]
Hi,

Thank you for your comment. 
We will try to list down the steps in README.
Regarding speed, it depends on many factors like GPU used, batch size, no. of epochs etc.

**Comment by khanrc** [comment]
Thanks for the quick reply.
I'll wait for the update :)
